### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by msmfa**
Replaced static answers with dropdown 'Show Answers'.

### CODE REVIEW

**Comment by msmfa** [comment]
Please add any other elements I can add dropboxes to. I wanted to confirm the style is acceptable before proceeding to change multiple elements. :)

**Comment by danieldelcore** [comment]
Hey @msmfa, that's perfect thank you so much for jumping in to do that!

**Comment by msmfa** [comment]
No worries. Let me know if there are any other areas I can add the drop-down(s) to.

**Comment by danieldelcore** [comment]
No worries 😄 
If you feel like it, you could add dropdowns to the remaining questions (that have answers). 
Would be great!

**Pull request merged**
